# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

# Xcode 27 only supports deployment targets from iOS 15.
platform :ios, '15.1'

# RN 0.73 writes NODE_BINARY to .xcode.env.local unquoted, which breaks script
# phases when node's path contains spaces. Write it quoted first.
xcode_env_local = File.join(__dir__, '.xcode.env.local')
unless File.exist?(xcode_env_local)
  node_binary = `node --print "process.argv[0]"`.strip
  File.write(xcode_env_local, "export NODE_BINARY=\"#{node_binary}\"\n")
end

prepare_react_native_project!

# If you are using a `react-native-flipper` your iOS build will fail when `NO_FLIPPER=1` is set.
# because `react-native-flipper` depends on (FlipperKit,...) that will be excluded
#
# To fix this you can also exclude `react-native-flipper` using a `react-native.config.js`
# ```js
# module.exports = {
#   dependencies: {
#     ...(process.env.NO_FLIPPER ? { 'react-native-flipper': { platforms: { ios: null } } } : {}),
# ```
# Flipper was removed from React Native after 0.73; keep it off.
flipper_config = FlipperConfiguration.disabled

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'ReactNativeFastImageExampleLegacy' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    :flipper_configuration => flipper_config,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'ReactNativeFastImageExampleLegacyTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |build_config|
        # Xcode 27 rejects deployment targets below iOS 15.
        if build_config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 15.0
          build_config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.1'
        end
        # fmt's consteval use doesn't compile with current Clang; build it as C++17.
        if target.name == 'fmt'
          build_config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++17'
        end
      end
    end
  end
end
